lucee-shibboleth:
  build: .
  environment:
    - "VIRTUAL_HOST=lucee-shibboleth.*"
  volumes:
    - ./www:/var/www
    - ./config/apache2/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf
    - ./config/shibboleth/shibboleth2-testshib.xml:/etc/shibboleth/shibboleth2.xml
    - ./logs/apache2:/var/log/apache2
    - ./logs/lucee:/opt/lucee/web/logs
    - ./logs/shibboleth:/var/log/shibboleth
    - ./logs/supervisor:/var/log/supervisor
    - ./logs/tomcat:/usr/local/tomcat/logs
