services:

  lucee-shibboleth:
    build: .
    environment:
      - "VIRTUAL_HOST=lucee-shibboleth.*"
    ports:
      - 80:80
    volumes:
      - /mnt/e/workbench/dae/lucee-shibboleth/www:/var/www
      - /mnt/e/workbench/dae/lucee-shibboleth/config/apache2/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - /mnt/e/workbench/dae/lucee-shibboleth/config/shibboleth3:/etc/shibboleth
      - /mnt/e/workbench/dae/lucee-shibboleth/logs/apache2:/var/log/apache2
      - /mnt/e/workbench/dae/lucee-shibboleth/logs/lucee:/opt/lucee/web/logs
      - /mnt/e/workbench/dae/lucee-shibboleth/logs/shibboleth:/var/log/shibboleth
      - /mnt/e/workbench/dae/lucee-shibboleth/logs/supervisor:/var/log/supervisor
      - /mnt/e/workbench/dae/lucee-shibboleth/logs/tomcat:/usr/local/tomcat/logs
